In [ ]:
# !pip3 install tensorflow-gpu

In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [3]:
### Sentences
sent = ["the glass of milk",
       "the glass of juice",
       "the cup of tea",
       "I am a good boy",
       "I am a good devloper",
       "understand the meaning of words",
       "your video is good"]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good devloper',
 'understand the meaning of words',
 'your video is good']

In [5]:
voc_size=10000

## One Hot Reperesentation

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[2369, 1532, 6682, 3946], [2369, 1532, 6682, 4276], [2369, 3804, 6682, 3095], [7274, 3262, 1771, 3999, 4543], [7274, 3262, 1771, 3999, 119], [1551, 2369, 496, 6682, 6169], [3747, 1225, 6873, 3999]]


## Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
# To make all the sentances size same 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2369 1532 6682 3946]
 [   0    0    0    0 2369 1532 6682 4276]
 [   0    0    0    0 2369 3804 6682 3095]
 [   0    0    0 7274 3262 1771 3999 4543]
 [   0    0    0 7274 3262 1771 3999  119]
 [   0    0    0 1551 2369  496 6682 6169]
 [   0    0    0    0 3747 1225 6873 3999]]


In [11]:
dim = 15

In [13]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))


In [16]:
#Adam optimizer with performace matrix as MSE
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

[[[ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784
    0.01763579 -0.01193316  0.03841796 -0.02573155  0.00927003
   -0.04456922  0.03807068 -0.03776709 -0.0067335  -0.02484951]
  [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784
    0.01763579 -0.01193316  0.03841796 -0.02573155  0.00927003
   -0.04456922  0.03807068 -0.03776709 -0.0067335  -0.02484951]
  [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784
    0.01763579 -0.01193316  0.03841796 -0.02573155  0.00927003
   -0.04456922  0.03807068 -0.03776709 -0.0067335  -0.02484951]
  [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784
    0.01763579 -0.01193316  0.03841796 -0.02573155  0.00927003
   -0.04456922  0.03807068 -0.03776709 -0.0067335  -0.02484951]
  [-0.0370607   0.00024696 -0.02288258 -0.00730827 -0.00313913
    0.01909152  0.01297713 -0.02957326 -0.04965682 -0.00296028
   -0.0177959   0.00674034 -0.02995558 -0.04914154 -0.02649176]
  [ 0.04549042 -0.02272474 -0.01720693  0.0472502 

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 2369, 1532, 6682, 3946], dtype=int32)

In [20]:
print(model.predict(embedded_docs)[0])

[[ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784  0.01763579
  -0.01193316  0.03841796 -0.02573155  0.00927003 -0.04456922  0.03807068
  -0.03776709 -0.0067335  -0.02484951]
 [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784  0.01763579
  -0.01193316  0.03841796 -0.02573155  0.00927003 -0.04456922  0.03807068
  -0.03776709 -0.0067335  -0.02484951]
 [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784  0.01763579
  -0.01193316  0.03841796 -0.02573155  0.00927003 -0.04456922  0.03807068
  -0.03776709 -0.0067335  -0.02484951]
 [ 0.04522376 -0.02819383 -0.01026791  0.02298012 -0.04380784  0.01763579
  -0.01193316  0.03841796 -0.02573155  0.00927003 -0.04456922  0.03807068
  -0.03776709 -0.0067335  -0.02484951]
 [-0.0370607   0.00024696 -0.02288258 -0.00730827 -0.00313913  0.01909152
   0.01297713 -0.02957326 -0.04965682 -0.00296028 -0.0177959   0.00674034
  -0.02995558 -0.04914154 -0.02649176]
 [ 0.04549042 -0.02272474 -0.01720693  0.0472502  -0.02293139  0.